# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: alphagenome_research/protos/calibration_scores.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'alphagenome_research/protos/calibration_scores.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from alphagenome.protos import dna_model_pb2 as alphagenome_dot_protos_dot_dna__model__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4alphagenome_research/protos/calibration_scores.proto\x12\x1b\x61lphagenome_research.protos\x1a\"alphagenome/protos/dna_model.proto\"\xa0\x01\n\x18VariantScorerCalibration\x12\x11\n\tquantiles\x18\x01 \x03(\x02\x12\x1e\n\x16quantile_probabilities\x18\x02 \x03(\x02\x12Q\n\x0ftracks_metadata\x18\x03 \x01(\x0b\x32\x38.google.gdm.gdmscience.alphagenome.v1main.TracksMetadata\"\xee\x01\n\x11\x43\x61librationScores\x12\x66\n\x15scorer_to_calibration\x18\x01 \x03(\x0b\x32G.alphagenome_research.protos.CalibrationScores.ScorerToCalibrationEntry\x1aq\n\x18ScorerToCalibrationEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x44\n\x05value\x18\x02 \x01(\x0b\x32\x35.alphagenome_research.protos.VariantScorerCalibration:\x02\x38\x01\x42\x42\n&com.google.alphagenome.research.protosB\x16\x43\x61librationScoresProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alphagenome_research.protos.calibration_scores_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n&com.google.alphagenome.research.protosB\026CalibrationScoresProtoP\001'
  _globals['_CALIBRATIONSCORES_SCORERTOCALIBRATIONENTRY']._loaded_options = None
  _globals['_CALIBRATIONSCORES_SCORERTOCALIBRATIONENTRY']._serialized_options = b'8\001'
  _globals['_VARIANTSCORERCALIBRATION']._serialized_start=122
  _globals['_VARIANTSCORERCALIBRATION']._serialized_end=282
  _globals['_CALIBRATIONSCORES']._serialized_start=285
  _globals['_CALIBRATIONSCORES']._serialized_end=523
  _globals['_CALIBRATIONSCORES_SCORERTOCALIBRATIONENTRY']._serialized_start=410
  _globals['_CALIBRATIONSCORES_SCORERTOCALIBRATIONENTRY']._serialized_end=523
# @@protoc_insertion_point(module_scope)
